#!/bin/bash
#
# test-drift.sh — Tier 2: upstream drift detection.
#
# UniFi regenerates the UDM's DNS configuration on settings changes, firmware
# updates and WAN lease renewals, and can reintroduce AdGuard as the UDM's own
# upstream resolver. If that happens the whole design goes quietly inert: the
# standby forwards into the very resolver that is down, so failover engages and
# achieves nothing.
#
# The daemon watches for this and logs it. Logging is EDGE-TRIGGERED — the
# check runs every INTERVAL, and a line per iteration would bury the transition
# under thousands of identical entries and defeat the purpose entirely.
#
# Induction is a temporary edit to the UDM's resolv file. That file lives on
# tmpfs and is regenerated by UniFi anyway, the original is captured and
# restored, and no client is affected at any point: the file governs only the
# UDM's own upstream resolution, and clients resolve through AdGuard directly.
#
# This scenario never engages failover, so there is no standby exposure and no
# maintenance window is required regardless of DHCP state.

set -u
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

hdr "Tier 2 — upstream drift is detected and logged once"

t2_preflight

t2_init

# No watchdog: this scenario cannot bind the standby, so there is no engaged
# duration to cap. Starting one would only add a spurious failure mode.

# ------------------------------------------------------------------
hdr "Baseline"
# ------------------------------------------------------------------

current="$(udm "cat '${RESOLV_FILE}' 2>/dev/null || true")"
if [ -z "$current" ]; then
    echo "ERROR: ${RESOLV_FILE} is empty or unreadable on the UDM." >&2
    exit 2
fi

if printf '%s\n' "$current" | awk -v ip="$ADGUARD_IP" '$1 == "nameserver" && $2 == ip { f = 1 } END { exit !f }'; then
    printf '\n\033[1;31mDRIFT IS ALREADY PRESENT\033[0m\n' >&2
    printf '%s already lists %s as an upstream. This is the real condition,\n' "$RESOLV_FILE" "$ADGUARD_IP" >&2
    printf 'not a test artifact — fix it in UniFi before testing detection of it.\n\n' >&2
    printf '%s\n\n' "$current" >&2
    exit 2
fi
_pass "${RESOLV_FILE} is clean to begin with"

register_restore "$RESOLV_FILE"

log_mark="$(daemon_log_lines)"

# ------------------------------------------------------------------
hdr "Induce drift"
# ------------------------------------------------------------------

udm "printf 'nameserver %s\n' '${ADGUARD_IP}' >> '${RESOLV_FILE}'"

if udm "grep -q '^nameserver ${ADGUARD_IP}\$' '${RESOLV_FILE}'"; then
    _pass "drift introduced into ${RESOLV_FILE}"
else
    _fail "could not introduce drift — nothing to detect"
    exit 1
fi

# Hold for several iterations. A per-iteration implementation produces one line
# per INTERVAL, so the window must be long enough to make that unmistakable.
hold=$(( INTERVAL * 4 ))
info "holding drift for ${hold}s (${hold}s / ${INTERVAL}s = 4 daemon iterations)"
sleep "$hold"

log_new="$(daemon_log_since "$log_mark")"
drift_lines="$(printf '%s' "$log_new" | grep -cF 'DRIFT  ' || true)"

assert_eq "DRIFT logged exactly once despite 4 iterations" "1" "$drift_lines"
if [ "$drift_lines" -gt 1 ]; then
    note "logging is not edge-triggered; a real drift event would be unreadable"
fi

if printf '%s' "$log_new" | grep -qF "$RESOLV_FILE"; then
    _pass "drift message names the offending file"
else
    _fail "drift message does not name ${RESOLV_FILE}"
fi

# ------------------------------------------------------------------
hdr "Blast radius"
# ------------------------------------------------------------------

assert "AdGuard still answers this workstation" adguard_answers
refute "standby stayed unbound (drift alone must not engage failover)" standby_bound

# ------------------------------------------------------------------
hdr "Clear drift"
# ------------------------------------------------------------------

_t2_restore_files

if udm "grep -q '^nameserver ${ADGUARD_IP}\$' '${RESOLV_FILE}'"; then
    _fail "drift still present after restore"
else
    _pass "${RESOLV_FILE} restored to its original contents"
fi

sleep "$(( INTERVAL * 3 ))"

log_new="$(daemon_log_since "$log_mark")"
cleared_lines="$(printf '%s' "$log_new" | grep -cF 'DRIFT CLEARED' || true)"
assert_eq "DRIFT CLEARED logged exactly once" "1" "$cleared_lines"

drift_lines="$(printf '%s' "$log_new" | grep -cF 'DRIFT  ' || true)"
assert_eq "still exactly one DRIFT line for the whole episode" "1" "$drift_lines"

summary
